version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/yesil_miras?sslmode=disable
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yesil_miras
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
